### ISSUE TITLE
i need the Elevated access?

### ISSUE THREAD

**Issue by Enzotoy** [davidteather/BackpackTf-API#5]
hello again (sorry :( )
i got a new things,
![image](https://user-images.githubusercontent.com/39483959/70343911-b7ea5d80-1858-11ea-9969-945b262c284e.png)
it is normal? i asked for a elevated acces yesterday but i didn't get respond

**Comment by davidteather** [comment]
It typically takes a few days to get elevated access I think I got an email when it got approved.

**Comment by Enzotoy** [comment]
ok, i see, ty. Bcz i'm blocked if i didn't get the acces :/
