### ISSUE TITLE
Did you know how to make this

### ISSUE THREAD

**Issue by Enzotoy** [davidteather/BackpackTf-API#6]
Hello @davidteather ,

i made this code and i want than the result of listings can be write on the listing.json but i don't know how to make this,
I tried to dump the result but nothing work :/

the code : 
![image](https://user-images.githubusercontent.com/39483959/70827897-88a09700-1dea-11ea-96de-6ea2f77ad9f6.png)

Ty for help

**Comment by davidteather** [comment]
Try to specify the tradable, craftable parameters and take out the other parameters that you are passing blank strings into.

**Comment by Enzotoy** [comment]
the fonction listings works, but he didn't write in the listings.json, i can see the result only by a "print(listings)"

**Comment by davidteather** [comment]
try

```
fischer = open("listings.json", "w")
json.dump(listings, fischer)
fischer.close()
```

**Comment by Enzotoy** [comment]
i tried and no, it's not worked :/

**Comment by davidteather** [comment]
maybe try

```
with open('listings.json', 'w') as outfile:
    json.dump(listings, outfile)
```

I'm closing this either way because it's not related to this api. Try googling "how to write json to file python"
