### ISSUE TITLE
itemPrice library error when API key is not valid

### ISSUE THREAD

**Issue by nbordin** [davidteather/BackpackTf-API#9]
The result should be verified when calling `item_price`: the variable `success` is not defined in the case when `jsondata['response']['success'] != 1`.

Traceback:

```python
price = api.itemPrice(name="Digit Divulger", quality="Unique", craftable=1, tradable=1)
  File "/home/a/.local/share/virtualenvs/steam-49pLg0Sz/lib/python3.7/site-packages/BackpackTF/currency.py", line 118, in item_price
    if success:
UnboundLocalError: local variable 'success' referenced before assignment
```

@davidteather

See: https://github.com/nbordin/BackpackTf-API/blob/master/BackpackTF/currency.py

**Comment by davidteather** [comment]
[Fixed](https://github.com/davidteather/BackpackTf-API/releases/tag/V0.1.3)
